# Script for populating the database. You can run it as:
#
#     mix run priv/repo/seeds.exs
#
# It is also run when you use `mix ecto.setup` or `mix ecto.reset`
#

alias Croc.Repo.Games.Monopoly.Card

users = [
  %{
    email: "jane.doe@example.com",
    password: "password",
    username: "Vladimir"
  },
  %{
    email: "john.smith@example.org",
    password: "password",
    username: "Somer"
  }
]

monopoly_cards = [
  %{
    name: "Start location",
    type: :start,
    position: 0,
    is_default: true,
    image_url: "some_image",
    loan_amount: 1000,
    buyout_cost: 1200,
    upgrade_cost: 1200,
    payment_amount: 1000,
    rarity: 0,
    upgrade_level_multipliers: [1.5, 1.2],
    max_upgrade_level: 2,
    cost: 1500
  },
  %{
    name: "Dior",
    monopoly_type: :perfume,
    type: :brand,
    position: 1,
    is_default: true,
    image_url: "some_image",
    loan_amount: 1000,
    buyout_cost: 1200,
    upgrade_cost: 1200,
    payment_amount: 1000,
    rarity: 0,
    upgrade_level_multipliers: [1.5, 1.2],
    max_upgrade_level: 2,
    cost: 1500
  },
  %{
    name: "Random event",
    type: :random_event,
    position: 2,
    is_default: true,
    image_url: "some_image",
    loan_amount: 1000,
    buyout_cost: 1200,
    upgrade_cost: 1200,
    payment_amount: 1000,
    rarity: 0,
    upgrade_level_multipliers: [1.5, 1.2],
    max_upgrade_level: 2,
    cost: 1500
  },
  %{
    name: "Givenchy",
    monopoly_type: :perfume,
    type: :brand,
    position: 3,
    is_default: true,
    image_url: "some_image",
    loan_amount: 1000,
    buyout_cost: 1200,
    upgrade_cost: 1200,
    payment_amount: 1000,
    rarity: 0,
    upgrade_level_multipliers: [1.5, 1.2],
    max_upgrade_level: 2,
    cost: 1500
  },
  %{
    name: "Payment",
    type: :payment,
    position: 4,
    is_default: true,
    image_url: "some_image",
    loan_amount: 1000,
    buyout_cost: 1200,
    upgrade_cost: 1200,
    payment_amount: 1000,
    rarity: 0,
    upgrade_level_multipliers: [1.5, 1.2],
    max_upgrade_level: 2,
    cost: 1500
  },
  %{
    name: "Land Rover",
    monopoly_type: :cars,
    type: :brand,
    position: 5,
    is_default: true,
    image_url: "some_image",
    loan_amount: 1000,
    buyout_cost: 1200,
    upgrade_cost: 1200,
    payment_amount: 1000,
    rarity: 0,
    upgrade_level_multipliers: [1.5, 1.2],
    max_upgrade_level: 2,
    cost: 1500
  },
  %{
    name: "ZARA",
    monopoly_type: :clothing,
    type: :brand,
    position: 6,
    is_default: true,
    image_url: "some_image",
    loan_amount: 1000,
    buyout_cost: 1200,
    upgrade_cost: 1200,
    payment_amount: 1000,
    rarity: 0,
    upgrade_level_multipliers: [1.5, 1.2],
    max_upgrade_level: 2,
    cost: 1500
  },
  %{
    name: "Random event",
    type: :random_event,
    position: 7,
    is_default: true,
    image_url: "some_image",
    loan_amount: 1000,
    buyout_cost: 1200,
    upgrade_cost: 1200,
    payment_amount: 1000,
    rarity: 0,
    upgrade_level_multipliers: [1.5, 1.2],
    max_upgrade_level: 2,
    cost: 1500
  },
  %{
    name: "Bershka",
    monopoly_type: :clothing,
    type: :brand,
    position: 8,
    is_default: true,
    image_url: "some_image",
    loan_amount: 1000,
    buyout_cost: 1200,
    upgrade_cost: 1200,
    payment_amount: 1000,
    rarity: 0,
    upgrade_level_multipliers: [1.5, 1.2],
    max_upgrade_level: 2,
    cost: 1500
  },
  %{
    name: "Reserved",
    monopoly_type: :clothing,
    type: :brand,
    position: 9,
    is_default: true,
    image_url: "some_image",
    loan_amount: 1000,
    buyout_cost: 1200,
    upgrade_cost: 1200,
    payment_amount: 1000,
    rarity: 0,
    upgrade_level_multipliers: [1.5, 1.2],
    max_upgrade_level: 2,
    cost: 1500
  },
  %{
    name: "Jail Cell",
    type: :jail_cell,
    position: 10,
    is_default: true,
    image_url: "some_image",
    loan_amount: 1000,
    buyout_cost: 1200,
    upgrade_cost: 1200,
    payment_amount: 1000,
    rarity: 0,
    upgrade_level_multipliers: [1.5, 1.2],
    max_upgrade_level: 2,
    cost: 1500
  },
  %{
    name: "Vkontakte",
    monopoly_type: :social_networks,
    type: :brand,
    position: 11,
    is_default: true,
    image_url: "some_image",
    loan_amount: 1000,
    buyout_cost: 1200,
    upgrade_cost: 1200,
    payment_amount: 1000,
    rarity: 0,
    upgrade_level_multipliers: [1.5, 1.2],
    max_upgrade_level: 2,
    cost: 1500
  },
  %{
    name: "Kodjima Production",
    monopoly_type: :games,
    type: :brand,
    position: 12,
    is_default: true,
    image_url: "some_image",
    loan_amount: 1000,
    buyout_cost: 1200,
    upgrade_cost: 1200,
    payment_amount: 1000,
    rarity: 0,
    upgrade_level_multipliers: [1.5, 1.2],
    max_upgrade_level: 2,
    cost: 1500
  },
  %{
    name: "Facebook",
    monopoly_type: :social_networks,
    type: :brand,
    position: 13,
    is_default: true,
    image_url: "some_image",
    loan_amount: 1000,
    buyout_cost: 1200,
    upgrade_cost: 1200,
    payment_amount: 1000,
    rarity: 0,
    upgrade_level_multipliers: [1.5, 1.2],
    max_upgrade_level: 2,
    cost: 1500
  },
  %{
    name: "Telegram",
    monopoly_type: :social_networks,
    type: :brand,
    position: 14,
    is_default: true,
    image_url: "some_image",
    loan_amount: 1000,
    buyout_cost: 1200,
    upgrade_cost: 1200,
    payment_amount: 1000,
    rarity: 0,
    upgrade_level_multipliers: [1.5, 1.2],
    max_upgrade_level: 2,
    cost: 1500
  },
  %{
    name: "Mazda",
    monopoly_type: :cars,
    type: :brand,
    position: 15,
    is_default: true,
    image_url: "some_image",
    loan_amount: 1000,
    buyout_cost: 1200,
    upgrade_cost: 1200,
    payment_amount: 1000,
    rarity: 0,
    upgrade_level_multipliers: [1.5, 1.2],
    max_upgrade_level: 2,
    cost: 1500
  },
  %{
    name: "Coca Cola",
    monopoly_type: :drinks,
    type: :brand,
    position: 16,
    is_default: true,
    image_url: "some_image",
    loan_amount: 1000,
    buyout_cost: 1200,
    upgrade_cost: 1200,
    payment_amount: 1000,
    rarity: 0,
    upgrade_level_multipliers: [1.5, 1.2],
    max_upgrade_level: 2,
    cost: 1500
  },
  %{
    name: "Random event",
    type: :random_event,
    position: 17,
    is_default: true,
    image_url: "some_image",
    loan_amount: 1000,
    buyout_cost: 1200,
    upgrade_cost: 1200,
    payment_amount: 1000,
    rarity: 0,
    upgrade_level_multipliers: [1.5, 1.2],
    max_upgrade_level: 2,
    cost: 1500
  },
  %{
    name: "Fanta",
    monopoly_type: :drinks,
    type: :brand,
    position: 18,
    is_default: true,
    image_url: "some_image",
    loan_amount: 1000,
    buyout_cost: 1200,
    upgrade_cost: 1200,
    payment_amount: 1000,
    rarity: 0,
    upgrade_level_multipliers: [1.5, 1.2],
    max_upgrade_level: 2,
    cost: 1500
  },
  %{
    name: "Sprite",
    monopoly_type: :drinks,
    type: :brand,
    position: 19,
    is_default: true,
    image_url: "some_image",
    loan_amount: 1000,
    buyout_cost: 1200,
    upgrade_cost: 1200,
    payment_amount: 1000,
    rarity: 0,
    upgrade_level_multipliers: [1.5, 1.2],
    max_upgrade_level: 2,
    cost: 1500
  },
  %{
    name: "Teleport",
    type: :teleport,
    position: 20,
    is_default: true,
    image_url: "some_image",
    loan_amount: 1000,
    buyout_cost: 1200,
    upgrade_cost: 1200,
    payment_amount: 1000,
    rarity: 0,
    upgrade_level_multipliers: [1.5, 1.2],
    max_upgrade_level: 2,
    cost: 1500
  },
  %{
    name: "Lufthansa",
    monopoly_type: :airports,
    type: :brand,
    position: 21,
    is_default: true,
    image_url: "some_image",
    loan_amount: 1000,
    buyout_cost: 1200,
    upgrade_cost: 1200,
    payment_amount: 1000,
    rarity: 0,
    upgrade_level_multipliers: [1.5, 1.2],
    max_upgrade_level: 2,
    cost: 1500
  },
  %{
    name: "Random event",
    type: :random_event,
    position: 22,
    is_default: true,
    image_url: "some_image",
    loan_amount: 1000,
    buyout_cost: 1200,
    upgrade_cost: 1200,
    payment_amount: 1000,
    rarity: 0,
    upgrade_level_multipliers: [1.5, 1.2],
    max_upgrade_level: 2,
    cost: 1500
  },
  %{
    name: "Aeroflot",
    monopoly_type: :airports,
    type: :brand,
    position: 23,
    is_default: true,
    image_url: "some_image",
    loan_amount: 1000,
    buyout_cost: 1200,
    upgrade_cost: 1200,
    payment_amount: 1000,
    rarity: 0,
    upgrade_level_multipliers: [1.5, 1.2],
    max_upgrade_level: 2,
    cost: 1500
  },
  %{
    name: "S7 Airlines",
    monopoly_type: :airports,
    type: :brand,
    position: 24,
    is_default: true,
    image_url: "some_image",
    loan_amount: 1000,
    buyout_cost: 1200,
    upgrade_cost: 1200,
    payment_amount: 1000,
    rarity: 0,
    upgrade_level_multipliers: [1.5, 1.2],
    max_upgrade_level: 2,
    cost: 1500
  },
  %{
    name: "Tesla",
    monopoly_type: :cars,
    type: :brand,
    position: 25,
    is_default: true,
    image_url: "some_image",
    loan_amount: 1000,
    buyout_cost: 1200,
    upgrade_cost: 1200,
    payment_amount: 1000,
    rarity: 0,
    upgrade_level_multipliers: [1.5, 1.2],
    max_upgrade_level: 2,
    cost: 1500
  },
  %{
    name: "MacDonalds",
    monopoly_type: :fastfood,
    type: :brand,
    position: 26,
    is_default: true,
    image_url: "some_image",
    loan_amount: 1000,
    buyout_cost: 1200,
    upgrade_cost: 1200,
    payment_amount: 1000,
    rarity: 0,
    upgrade_level_multipliers: [1.5, 1.2],
    max_upgrade_level: 2,
    cost: 1500
  },
  %{
    name: "KFC",
    monopoly_type: :fastfood,
    type: :brand,
    position: 27,
    is_default: true,
    image_url: "some_image",
    loan_amount: 1000,
    buyout_cost: 1200,
    upgrade_cost: 1200,
    payment_amount: 1000,
    rarity: 0,
    upgrade_level_multipliers: [1.5, 1.2],
    max_upgrade_level: 2,
    cost: 1500
  },
  %{
    name: "KONAMI",
    monopoly_type: :games,
    type: :brand,
    position: 28,
    is_default: true,
    image_url: "some_image",
    loan_amount: 1000,
    buyout_cost: 1200,
    upgrade_cost: 1200,
    payment_amount: 1000,
    rarity: 0,
    upgrade_level_multipliers: [1.5, 1.2],
    max_upgrade_level: 2,
    cost: 1500
  },
  %{
    name: "Burger King",
    monopoly_type: :fastfood,
    type: :brand,
    position: 29,
    is_default: true,
    image_url: "some_image",
    loan_amount: 1000,
    buyout_cost: 1200,
    upgrade_cost: 1200,
    payment_amount: 1000,
    rarity: 0,
    upgrade_level_multipliers: [1.5, 1.2],
    max_upgrade_level: 2,
    cost: 1500
  },
  %{
    name: "Prison",
    type: :prison,
    position: 30,
    is_default: true,
    image_url: "some_image",
    loan_amount: 1000,
    buyout_cost: 1200,
    upgrade_cost: 1200,
    payment_amount: 1000,
    rarity: 0,
    upgrade_level_multipliers: [1.5, 1.2],
    max_upgrade_level: 2,
    cost: 1500
  },
  %{
    name: "Hyatt",
    monopoly_type: :hotels,
    type: :brand,
    position: 31,
    is_default: true,
    image_url: "some_image",
    loan_amount: 1000,
    buyout_cost: 1200,
    upgrade_cost: 1200,
    payment_amount: 1000,
    rarity: 0,
    upgrade_level_multipliers: [1.5, 1.2],
    max_upgrade_level: 2,
    cost: 1500
  },
  %{
    name: "Hilton",
    monopoly_type: :hotels,
    type: :brand,
    position: 32,
    is_default: true,
    image_url: "some_image",
    loan_amount: 1000,
    buyout_cost: 1200,
    upgrade_cost: 1200,
    payment_amount: 1000,
    rarity: 0,
    upgrade_level_multipliers: [1.5, 1.2],
    max_upgrade_level: 2,
    cost: 1500
  },
  %{
    name: "Random event",
    type: :random_event,
    position: 33,
    is_default: true,
    image_url: "some_image",
    loan_amount: 1000,
    buyout_cost: 1200,
    upgrade_cost: 1200,
    payment_amount: 1000,
    rarity: 0,
    upgrade_level_multipliers: [1.5, 1.2],
    max_upgrade_level: 2,
    cost: 1500
  },
  %{
    name: "Novotel",
    monopoly_type: :hotels,
    type: :brand,
    position: 34,
    is_default: true,
    image_url: "some_image",
    loan_amount: 1000,
    buyout_cost: 1200,
    upgrade_cost: 1200,
    payment_amount: 1000,
    rarity: 0,
    upgrade_level_multipliers: [1.5, 1.2],
    max_upgrade_level: 2,
    cost: 1500
  },
  %{
    name: "Ford",
    monopoly_type: :cars,
    type: :brand,
    position: 35,
    is_default: true,
    image_url: "some_image",
    loan_amount: 1000,
    buyout_cost: 1200,
    upgrade_cost: 1200,
    payment_amount: 1000,
    rarity: 0,
    upgrade_level_multipliers: [1.5, 1.2],
    max_upgrade_level: 2,
    cost: 1500
  },
  %{
    name: "Debt",
    type: :payment,
    position: 36,
    is_default: true,
    image_url: "some_image",
    loan_amount: 1000,
    buyout_cost: 1200,
    upgrade_cost: 1200,
    payment_amount: 1000,
    rarity: 0,
    upgrade_level_multipliers: [1.5, 1.2],
    max_upgrade_level: 2,
    cost: 1500
  },
  %{
    name: "Apple",
    monopoly_type: :phones,
    type: :brand,
    position: 37,
    is_default: true,
    image_url: "some_image",
    loan_amount: 1000,
    buyout_cost: 1200,
    upgrade_cost: 1200,
    payment_amount: 1000,
    rarity: 0,
    upgrade_level_multipliers: [1.5, 1.2],
    max_upgrade_level: 2,
    cost: 1500
  },
  %{
    name: "Motorola",
    monopoly_type: :phones,
    type: :brand,
    position: 37,
    is_default: true,
    image_url: "some_image",
    loan_amount: 1000,
    buyout_cost: 1200,
    upgrade_cost: 1200,
    payment_amount: 1000,
    rarity: 0,
    upgrade_level_multipliers: [1.5, 1.2],
    max_upgrade_level: 2,
    cost: 1500
  },
  %{
    name: "Random event",
    type: :random_event,
    position: 38,
    is_default: true,
    image_url: "some_image",
    loan_amount: 1000,
    buyout_cost: 1200,
    upgrade_cost: 1200,
    payment_amount: 1000,
    rarity: 0,
    upgrade_level_multipliers: [1.5, 1.2],
    max_upgrade_level: 2,
    cost: 1500
  },
  %{
    name: "Xiaomi",
    monopoly_type: :phones,
    type: :brand,
    position: 39,
    is_default: true,
    image_url: "some_image",
    loan_amount: 1000,
    buyout_cost: 1200,
    upgrade_cost: 1200,
    payment_amount: 1000,
    rarity: 0,
    upgrade_level_multipliers: [1.5, 1.2],
    max_upgrade_level: 2,
    cost: 1500
  },
]

for card <- monopoly_cards do
  {:ok, monopoly_card} = Card.create(%Card{}, card)
end


for user <- users do
  {:ok, user} = Croc.Accounts.create_user(user)
  Croc.Accounts.confirm_user(user)
end
